version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres-db
    networks:
      - backend
    restart: unless-stopped


  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-server
      - postgres-db
    networks:
      - backend
    restart: unless-stopped

  expense-service:
    build: ./expense-service
    container_name: expense-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-server
      - postgres-db
    networks:
      - backend
    restart: unless-stopped

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-server
      - postgres-db
    networks:
      - backend
    restart: unless-stopped

  report-service:
    build: ./report-service
    container_name: report-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-server
      - postgres-db
    networks:
      - backend
    restart: unless-stopped
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-server
      - user-service
      - expense-service
      - billing-service
      - report-service
    networks:
      - backend
    restart: unless-stopped
networks:
  backend:
    driver: bridge
