server:
  port: 8081
spring:
  application:
     name: user-service
  datasource:
     url: jdbc:postgresql://localhost:5432/user_service_db
     username: postgres
     password: tiger
  jpa:
     hibernate:
        ddl-auto: update
     show-sql: true
     datbase-platform: org.hibernate.dialect.PostgreSQLDialect
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true