spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/billing_service_db
    username: postgres
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
