spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/billing_service_db
    username: postgres
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
