name: Java CI with Maven

on:
  push:
    branches: [ "master" ]  # Run when code is pushed to master
  pull_request:
    branches: [ "master" ]  # Or pull requests to master

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub gives you a Linux VM

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build User Service
      run: mvn clean install -DskipTests -f user-service/pom.xml

    - name: Build Expense Service
      run: mvn clean install -DskipTests -f expense-service/pom.xml

    - name: Build Billing Service
      run: mvn clean install -DskipTests -f billing-service/pom.xml

    - name: Build Report Service
      run: mvn clean install -DskipTests -f report-service/pom.xml